services:
  secure-apache:
    build: ./apache
    ports:
      - "8090:8090"
      - "443:443"
    env_file:
      - config.env
    container_name: secure-apache
    depends_on:
      - mysql
      - phpmyadmin
    networks:
      - app_network

  mysql:
    image: mysql:5.7
    env_file:
      - config.env
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - config.env
    environment:
      - PMA_ABSOLUTE_URI=https://phpmyadmin.local/
    container_name: phpmyadmin
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql-data:
